### ISSUE TITLE
DRM_IOCTL_MODE_CREATE_DUMB failed: Cannot allocate memory

### ISSUE THREAD

**Issue by stephenlang84** [MirServer/mir-kiosk-apps#16]
Hi

I'm trying to build an application that will run on Raspberry Pi 4, Ubuntu Core 20.04 OS, a 4K monitor. I followed the [snapcraft.yaml](https://github.com/MirServer/mir-kiosk-apps/blob/master/snap/snapcraft.yaml) But I got this runtime error 
`DRM_IOCTL_MODE_CREATE_DUMB failed: Cannot allocate memory`

I also installed [mir-kiosk-apps snap](https://snapcraft.io/install/mir-kiosk-apps/ubuntu) on my Raspberry Pi 4, but I got the same error.

But when I install my snap application, ubuntu-frame on Raspberry Pi OS, I can run my application on the ubuntu frame in a smaller window not full screen 4k.

Can you give me an advice ? How can I run my snap application on Ubuntu Core + 4K screen ?

Thanks.

**Comment by AlanGriffiths** [comment]
I think the immediate problem is using `core18`: the RPi4 graphics is more recent than the version of Mesa in 18.04.

But you shouldn't be following this example, look here:

https://github.com/MirServer/iot-example-graphical-snap/wiki/Embedding-IOT-GUI-with-Ubuntu-Frame

**Comment by stephenlang84** [comment]
> I think the immediate problem is using `core18`: the RPi4 graphics is more recent than the version of Mesa in 18.04.
> 
> But you shouldn't be following this example, look here:
> 
> https://github.com/MirServer/iot-example-graphical-snap/wiki/Embedding-IOT-GUI-with-Ubuntu-Frame

Thank you @AlanGriffiths
