### ISSUE TITLE
"photoviewer" app doesn't show any photos

### ISSUE THREAD

**Issue by AlanGriffiths** [MirServer/mir-kiosk-apps#5]
This was in testing on RPi3/core18, but as other apps (e.g. rssnews) work fine I suspect this is app specific. Has the underlying website changed?

**Comment by AlanGriffiths** [comment]
Actually, StocQt doesn't get any data either.

**Comment by gerboland** [comment]
Confirmed photoviewer app failing to show images on Qt5.9. I believe it is due to flicker API having changed to return https URIs to images, but photoviewer expecting http.

**Comment by AlanGriffiths** [comment]
Simplest to update our set of examples.

There's stuff I've got working in egmde-confined-desktop and mit-test-tools that I can replace these examples with.
